spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwtSecretKey=dsfawef2q&^%$#@!sdfvwrfAWEDGzserxdctfygvbhuinjokm,l!@#$%^&*(dfugwie@$DFergwef84652654843q4gqerfqw3t143?><+#%@$egetwer34gf3g3gyj465ejhrfdsgverthwethbrtheq5y@#%#%^%$#@$%Q#REGW$%Y#Y%6234qrfwergfwu7y245rgewr

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=12637694552-o1ioj9qdo46s6s4fhepdc740di1k3iru.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile

